mode: single
blueprint:
  name: IKEA BILRESA Dual Button
  author: Skaronator
  description: >
    Full-featured automation for the IKEA BILRESA dual-button remote.
    Supports single press, double press, and long press for both buttons.
    Version 1.1.0
  domain: automation
  source_url: https://raw.githubusercontent.com/Skaronator/home-assistant-blueprints/refs/heads/main/automation/ikea-bilresa-dual-button.yaml
  homeassistant:
    min_version: 2025.12.0

  input:
    setup:
      name: Button Setup
      description: >
        Select the event entities for all 2 buttons on the IKEA BILRESA dual-button remote.
      input:
        button1_event:
          name: Button 1 – Entity
          description: >
            Select the event entity for Button 1
          selector: &button_event_selector
            entity:
              filter:
                integration: matter
                domain: event
                device_class: button

        button2_event:
          name: Button 2 – Entity
          description: >
            Select the event entity for Button 2
          selector: *button_event_selector

    button1:
      name: Button 1 Actions
      description: >
        Define actions when pressing Button 1.
      input:
        button1_single:
          name: Button 1 – Single Press
          description: Action for Button 1 single press (multi_press_1).
          default: []
          selector:
            action: {}

        button1_double:
          name: Button 1 – Double Press
          description: Action for Button 1 double press (multi_press_2).
          default: []
          selector:
            action: {}

        button1_long_press:
          name: Button 1 – Long Press (on press)
          description: Action for Button 1 long press completion (long_press).
          default: []
          selector:
            action: {}

        button1_long_release:
          name: Button 1 – Long Press (on release)
          description: Action for Button 1 long press completion (long_release).
          default: []
          selector:
            action: {}

        button1_holding_interval:
          name: Button 1 – Holding Interval (seconds)
          description: Interval in seconds for repeating "while holding" actions.
          default: 0.2
          selector:
            number:
              min: 0.05
              max: 2
              step: 0.05

        button1_while_holding:
          name: Button 1 – While Holding
          description: Action for Button 1 while holding. This action will be repeated at the defined interval while the button is held down.
          default: []
          selector:
            action: {}
        
    button2:
      name: Button 2 Actions
      description: >
        Define actions when pressing Button 2.
      input:
        button2_single:
          name: Button 2 – Single Press
          description: Action for Button 2 single press (multi_press_1).
          default: []
          selector:
            action: {}

        button2_double:
          name: Button 2 – Double Press
          description: Action for Button 2 double press (multi_press_2).
          default: []
          selector:
            action: {}

        button2_long_press:
          name: Button 2 – Long Press (on press)
          description: Action for Button 2 long press completion (long_press).
          default: []
          selector:
            action: {}

        button2_long_release:
          name: Button 2 – Long Press (on release)
          description: Action for Button 2 long press completion (long_release).
          default: []
          selector:
            action: {}

        button2_holding_interval:
          name: Button 2 – Holding Interval (seconds)
          description: Interval in seconds for repeating "while holding" actions.
          default: 0.2
          selector:
            number:
              min: 0.05
              max: 2
              step: 0.05

        button2_while_holding:
          name: Button 2 – While Holding
          description: Action for Button 2 while holding. This action will be repeated at the defined interval while the button is held down.
          default: []
          selector:
            action: {}

trigger:
  - platform: state
    id: button1
    entity_id: !input button1_event
  - platform: state
    id: button2
    entity_id: !input button2_event

condition:
  - condition: template
    value_template: >
      {{ trigger.from_state.state not in ['unknown', 'unavailable'] }}
  - condition: template
    value_template: >
      {{ trigger.to_state.state not in ['unknown', 'unavailable'] }}
  - condition: template
    value_template: >
      {{ trigger.from_state.state != trigger.to_state.state }}

action:
  - variables:
      trigger_id: "{{ trigger.id }}"
      press_type: "{{ trigger.to_state.attributes.event_type }}"

  - parallel:
      - repeat:
          while:
            - condition: template
              value_template: >
                {{ press_type == 'long_press' and trigger_id == 'button1' and states(trigger.entity_id) == trigger.to_state.state }}
          sequence:
            - delay:
                seconds: !input button1_holding_interval
            - choose:
                - conditions:
                    - condition: template
                      value_template: >
                        {{ press_type == 'long_press' and trigger_id == 'button1' and states(trigger.entity_id) == trigger.to_state.state }}
                  sequence: !input button1_while_holding

      - repeat:
          while:
            - condition: template
              value_template: >
                {{ press_type == 'long_press' and trigger_id == 'button2' and states(trigger.entity_id) == trigger.to_state.state }}
          sequence:
            - delay:
                seconds: !input button2_holding_interval
            - choose:
                - conditions:
                    - condition: template
                      value_template: >
                        {{ press_type == 'long_press' and trigger_id == 'button2' and states(trigger.entity_id) == trigger.to_state.state }}
                  sequence: !input button2_while_holding

      - choose:
          # Button 1 Actions
          - conditions:
              - condition: template
                value_template: >
                  {{ trigger_id == 'button1' and press_type == 'multi_press_1' }}
            sequence: !input button1_single

          - conditions:
              - condition: template
                value_template: >
                  {{ trigger_id == 'button1' and press_type == 'multi_press_2' }}
            sequence: !input button1_double

          - conditions:
              - condition: template
                value_template: >
                  {{ trigger_id == 'button1' and press_type == 'long_press' }}
            sequence: !input button1_long_press

          - conditions:
              - condition: template
                value_template: >
                  {{ trigger_id == 'button1' and press_type == 'long_release' }}
            sequence: !input button1_long_release

          # Button 2 Actions
          - conditions:
              - condition: template
                value_template: >
                  {{ trigger_id == 'button2' and press_type == 'multi_press_1' }}
            sequence: !input button2_single

          - conditions:
              - condition: template
                value_template: >
                  {{ trigger_id == 'button2' and press_type == 'multi_press_2' }}
            sequence: !input button2_double

          - conditions:
              - condition: template
                value_template: >
                  {{ trigger_id == 'button2' and press_type == 'long_press' }}
            sequence: !input button2_long_press

          - conditions:
              - condition: template
                value_template: >
                  {{ trigger_id == 'button2' and press_type == 'long_release' }}
            sequence: !input button2_long_release
